name: publish
env:
    CI: true
on:
    push:
        branches:
            - master
        tags:
            - "!*"
jobs:
    release:
        name: Setup
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v1
            - name: setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
                  registry-url: "https://npm.pkg.github.com"
            - name: install
              run: npm install
            # Publish to npm if this version is not published
            - name: Publish
              run: |
                  npx can-npm-publish --verbose && npm publish || echo "Does not publish"
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            # Push tag to GitHub if the version's tag is not tagged
            - name: package-version-to-git-tag
              uses: azu/action-package-version-to-git-tag@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  github_repo: ${{ github.repository }}
                  git_commit_sha: ${{ github.sha }}
